### ISSUE TITLE
Duplikasi gambar section klien

### ISSUE THREAD

**Issue by Gudangsoft** [Gudangsoft/gudangsoft.net#2]
logo pada slide ketiga terduplikasi,@aripdevel  segera di perbaiki.

**Comment by aripdev** [comment]
bug sudah diperbaiki @Gudangsoft [cek](https://github.com/Gudangsoft/gudangsoft.net/commit/12fbe03cf46845e30982bc4a398667f65db407e5)

**Comment by aripdev** [comment]
done #3
